_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": darwin-arm64
discount:
    value: 0.9
env:
    value: CartPole-v1
learning_rate:
    value: 0.00025
n_episodes:
    value: 100
num_eval_episodes:
    value: 10
seed:
    value: 42
step_size:
    value: 0.01
use_wandb:
    value: true
